CREATE USER INVENTA6 IDENTIFIED BY inventa6 DEFAULT TABLESPACE USERS;
GRANT CONNECT, RESOURCE, DBA TO INVENTA6;
GRANT CREATE SESSION TO INVENTA6;
GRANT ALL PRIVILEGES TO INVENTA6 IDENTIFIED BY inventa6;
GRANT UNLIMITED TABLESPACE TO INVENTA6;